language: rust
rust:
    - stable
    - beta
    - nightly

addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-4.8
        - libsnappy-dev
        - realpath
        - pkg-config

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

cache: cargo

before_install:
    - export CC="gcc-4.8"
    - git clone https://github.com/openvenues/libpostal
    - cd libpostal
    - ./bootstrap.sh
    - ./configure --datadir=$(pwd)/data
    - sudo make install
    - cd ..
    - sudo ldconfig

script:
  - cargo build --verbose --all
  - cargo test --verbose --all -- --test-threads 1
  - cargo bench
